services:
  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8080:8080"
    environment:
      - IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL}
      - IMAGE_SERVICE_URL=${IMAGE_SERVICE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    depends_on:
      - identity_service
      - image_service
      - word_service
    networks:
      - service_app_network

  identity_service:
    build:
      context: ./identity_service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
      - JWT_OTP_SECRET=${JWT_OTP_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - API_GATEWAY=${API_GATEWAY}
      - WORD_FILTER_SERVICE_URL=${WORD_FILTER_SERVICE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    networks:
      - service_app_network

  word_service:
    build:
      context: ./word_filter_service
    ports:
      - "8082:8082"
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    networks:
      - service_app_network

  image_service:
    build:
      context: ./image_check
    ports:
      - "8083:8083"
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    networks:
      - service_app_network

networks:
  service_app_network:
