services:
  - type: web
    name: api_gateway
    env: docker
    plan: free
    dockerfilePath: ./api_gateway/Dockerfile
    envVars:
      - fromGroup: service-app-env

  - type: web
    name: identity_service
    env: docker
    plan: free
    dockerfilePath: ./identity_service/Dockerfile
    envVars:
      - fromGroup: service-app-env
    buildFilter:
      paths:
        - identity_service/**

  - type: web
    name: word_service
    env: docker
    plan: free
    dockerfilePath: ./word_filter_service/Dockerfile
    envVars:
      - fromGroup: service-app-env
    buildFilter:
      paths:
        - word_service/**

  - type: web
    name: image_service
    env: docker
    plan: free
    dockerfilePath: ./image_check/Dockerfile
    envVars:
      - fromGroup: service-app-env
    buildFilter:
      paths:
        - word_service/**
